//
//  PlacesRouter.swift
//  Places
//
//  Created Sebastian Cancinos on 22/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PlacesRouter: PlacesWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = PlacesViewController(nibName: "PlacesViewController", bundle: nil)
        let interactor = PlacesInteractor()
        let router = PlacesRouter()
        let presenter = PlacesPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        let datasource = NetworkDataSource()
        datasource.urlSession = URLSession.shared
        interactor.dataSource = datasource

        let collectionDatasource = PlacesDatasource()
        view.datasource = collectionDatasource

        collectionDatasource.delegate = view

        return view
    }

    func show(_ location: Location) {
        DispatchQueue.main.async {[weak self] in
            let detailView = PlaceDetailRouter.createModule(for: location)
            self?.viewController?.navigationController?.pushViewController(detailView, animated: true)
        }
    }
}
