//
//  PlaceDetailViewController.swift
//  Places
//
//  Created Sebastian Cancinos on 23/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import FloatRatingView

class PlaceDetailViewController: UIViewController, PlaceDetailViewProtocol {

	var presenter: PlaceDetailPresenterProtocol?
    @IBOutlet weak var photoStack: UIStackView!
    @IBOutlet weak var photoScroll: UIScrollView!
    @IBOutlet weak var ratingView: FloatRatingView!
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var addressLabel: UILabel!
    @IBOutlet weak var typesLabel: UILabel!

	override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.ready()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)

        self.navigationController?.setNavigationBarHidden(false,
                                                   animated: animated)
    }
}
