//
//  PlaceDetailInteractor.swift
//  Places
//
//  Created Sebastian Cancinos on 23/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PlaceDetailInteractor: PlaceDetailInteractorInputProtocol {

    weak var presenter: PlaceDetailInteractorOutputProtocol?
    var dataSource: ImageProviderDataSource?
    var model: Location?

    func loadLocation() {
        guard let location = model else { return }

        presenter?.show(location: location)

        if let photos = location.photos {
            for photo in photos {
                dataSource?.getImage(with: photo.reference) {[weak self]  result in
                    switch result {
                    case .success(let image):
                        self?.presenter?.add(photo: image)

                    case .failure:
                        break
                    }
                }
            }
        }
    }
}
