//
//  PlaceDetailRouter.swift
//  Places
//
//  Created Sebastian Cancinos on 23/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PlaceDetailRouter: PlaceDetailWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(for location: Location) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = PlaceDetailViewController(nibName: nil, bundle: nil)
        let interactor = PlaceDetailInteractor()
        let router = PlaceDetailRouter()
        let presenter = PlaceDetailPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        let datasource = NetworkDataSource()
        datasource.urlSession = URLSession.shared
        interactor.dataSource = datasource

        interactor.model = location
        return view
    }
}
