//
//  PlacesCellViewController.swift
//  Places
//
//  Created Sebastian Cancinos on 22/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import FloatRatingView

class PlacesCellView: UICollectionViewCell, PlacesCellViewProtocol {

	var presenter: PlacesCellPresenterProtocol?

    @IBOutlet weak var placeImage: UIImageView!
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var addressLabel: UILabel!
    @IBOutlet weak var openLabel: UILabel!
    @IBOutlet weak var ratingView: FloatRatingView!
    @IBOutlet weak var imageLoadingIndicator: UIActivityIndicatorView!

    override func prepareForReuse() {
        placeImage.image = nil
        nameLabel.text = ""
        addressLabel.text = ""
        ratingView.isHidden = false
        ratingView.rating = 0

        imageLoadingIndicator.stopAnimating()
    }
}
