//
//  PlacesCellInteractor.swift
//  Places
//
//  Created Sebastian Cancinos on 22/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PlacesCellInteractor: PlacesCellInteractorInputProtocol {
    var dataSource: ImageProviderDataSource?
    weak var presenter: PlacesCellInteractorOutputProtocol?

    var model: Location?

    func loadLocation() {
        guard let location = model else { return }

        presenter?.show(location)

        guard let imageRef = location.photos?.first?.reference else { return }
        dataSource?.getImage(with: imageRef) {[weak self]  result in
            switch result {
            case .success(let image):
                self?.presenter?.update(photo: image)

            case .failure:
//                self.presenter?.present(error: error)
                break
            }
        }
    }
}
