//
//  PlacesCellProtocols.swift
//  Places
//
//  Created Sebastian Cancinos on 22/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit
import FloatRatingView

// MARK: Wireframe -
protocol PlacesCellWireframeProtocol: class {

}
// MARK: Presenter -
protocol PlacesCellPresenterProtocol: class {
    var interactor: PlacesCellInteractorInputProtocol? { get set }

    func ready()
}

// MARK: Interactor -
protocol PlacesCellInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func show(_ model: Location)
    func update(photo: UIImage)
}

protocol PlacesCellInteractorInputProtocol: class {

    var presenter: PlacesCellInteractorOutputProtocol? { get set }
    var dataSource: ImageProviderDataSource? { get set }

    /* Presenter -> Interactor */
    func loadLocation()
}

// MARK: View -
protocol PlacesCellViewProtocol: class {

    var presenter: PlacesCellPresenterProtocol? { get set }

    /* Presenter -> View */
    var placeImage: UIImageView! {get set}
    var nameLabel: UILabel! {get set}
    var addressLabel: UILabel! {get set}
    var openLabel: UILabel! {get set}
    var ratingView: FloatRatingView! {get set}
    var imageLoadingIndicator: UIActivityIndicatorView! {get set}

}
