//
//  PlacesCellPresenter.swift
//  Places
//
//  Created Sebastian Cancinos on 22/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import FloatRatingView

class PlacesCellPresenter: PlacesCellPresenterProtocol, PlacesCellInteractorOutputProtocol {

    weak private var view: PlacesCellViewProtocol?
    var interactor: PlacesCellInteractorInputProtocol?
    private let router: PlacesCellWireframeProtocol

    init(interface: PlacesCellViewProtocol, interactor: PlacesCellInteractorInputProtocol?, router: PlacesCellWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func show(_ model: Location) {
        view?.nameLabel.text = model.name
        view?.addressLabel.text = model.vicinity
        if let rating = model.rating {
            view?.ratingView.rating = Double(rating)
        } else {
            view?.ratingView.isHidden = true
        }

        if let openhours = model.openHours, openhours.openNow {
            view?.openLabel.text = "OPEN"
        } else {
            view?.openLabel.text = "CLOSED"
        }
    }

    func update(photo: UIImage) {
        DispatchQueue.main.async {[weak self]  in
            self?.view?.imageLoadingIndicator.stopAnimating()
            self?.view?.placeImage.image = photo
        }
    }

    func ready() {
        view?.imageLoadingIndicator.startAnimating()
        interactor?.loadLocation()
    }
}
