//
//  PlacesInteractorMock.swift
//  Places
//
//  Created Sebastian Cancinos on 25/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
@testable import Places

class PlacesInteractorMock {
    var presenter: PlacesInteractorOutputProtocol?

    var loadLocationsCalled = false
    var loadNextLocationsCalled = false
    var typeOfLocationsToLoad: LocationType?
    var locationForDetails: Location?
}

extension PlacesInteractorMock: PlacesInteractorInputProtocol {
    func loadDetails(for location: Location) {
        locationForDetails = location
    }

    func loadLocations(by type: LocationType) {
        typeOfLocationsToLoad = type
    }

    func loadLocations() {
        loadLocationsCalled = true
    }

    func loadNextLocations() {
        loadNextLocationsCalled = true
    }
}
