//
//  PlacesPresenterMock.swift
//  Places
//
//  Created Sebastian Cancinos on 25/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
@testable import Places

class PlacesPresenterMock {
    var interactor: PlacesInteractorInputProtocol?

    var readyCalled = false
    var refreshCalled = false
    var infiniteScrollCalled = false
    var locationSelected: Location?
    var typeToFilter: LocationType?
    var locationsPresented: [Location]?
    var locationDetailsToPresent: Location?
    var errorPresented: Error?
}

extension PlacesPresenterMock: PlacesPresenterProtocol {
    func filter(by type: LocationType) {
        typeToFilter = type
    }

    func ready() {
        readyCalled = true
    }

    func refresh() {
        refreshCalled = true
    }

    func select(_ location: Location) {
        locationSelected = location
    }

    func infiniteScroll() {
        infiniteScrollCalled = true
    }
}

extension PlacesPresenterMock: PlacesInteractorOutputProtocol {
    func presentDetails(for location: Location) {
        locationDetailsToPresent = location
    }

    func present(locations: [Location]) {
        locationsPresented = locations
    }

    func present(error: Error) {
        errorPresented = error
    }
}
