//
//  PlacesViewControllerMock.swift
//  Places
//
//  Created Sebastian Cancinos on 25/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
@testable import Places

class PlacesViewControllerMock: UIViewController {
	var presenter: PlacesPresenterProtocol?
    var locationsUpdated: [Location]?
    var errorShown: Error?
}

extension PlacesViewControllerMock: PlacesViewProtocol {
    func update(locations: [Location]) {
        locationsUpdated = locations
    }

    func show(error: Error) {
        errorShown = error
    }
}
