//
//  PlacesRouterMock.swift
//  Places
//
//  Created Sebastian Cancinos on 25/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
@testable import Places

class PlacesRouterMock {
    var viewController: UIViewController?
    var locationShown: Location?
}

extension PlacesRouterMock: PlacesWireframeProtocol {
    func show(_ location: Location) {
        locationShown = location
    }
}
