//
//  PlaceDetailViewControllerMock.swift
//  Places
//
//  Created Sebastian Cancinos on 25/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import FloatRatingView
@testable import Places

class PlaceDetailViewControllerMock: UIViewController {
    var presenter: PlaceDetailPresenterProtocol?
    var photoStack: UIStackView!
    var photoScroll: UIScrollView!
    var ratingView: FloatRatingView!
    var nameLabel: UILabel!
    var addressLabel: UILabel!
    var typesLabel: UILabel!
}

extension PlaceDetailViewControllerMock: PlaceDetailViewProtocol {

}
