//
//  PlaceDetailInteractorMock.swift
//  Places
//
//  Created Sebastian Cancinos on 25/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
@testable import Places

class PlaceDetailInteractorMock {
    weak var presenter: PlaceDetailInteractorOutputProtocol?
    var model: Location?

    var loadLocationCalled = false
}

extension PlaceDetailInteractorMock: PlaceDetailInteractorInputProtocol {
    func loadLocation() {
        loadLocationCalled = true
    }
}
