//
//  PlaceDetailPresenterMock.swift
//  Places
//
//  Created Sebastian Cancinos on 25/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
@testable import Places

class PlaceDetailPresenterMock {
    var readyCalled = false
    var interactor: PlaceDetailInteractorInputProtocol?
    var placeShown: Location?
    var lastPhotoAdded: UIImage?
    var photoCount = 0
}

extension PlaceDetailPresenterMock: PlaceDetailPresenterProtocol {
    func ready() {
        readyCalled = true
    }
}

extension PlaceDetailPresenterMock: PlaceDetailInteractorOutputProtocol {
    func show(location: Location) {
        placeShown = location
    }

    func add(photo: UIImage) {
        lastPhotoAdded = photo
        photoCount += 1
    }
}
