//
//  PlaceDetailRouterMock.swift
//  Places
//
//  Created Sebastian Cancinos on 25/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
@testable import Places

class PlaceDetailRouterMock {
    weak var viewController: UIViewController?
}

extension PlaceDetailRouterMock: PlaceDetailWireframeProtocol {

}
