//
//  PlaceTypesCellPresenter.swift
//  Places
//
//  Created Sebastian Cancinos on 22/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PlaceTypesCellPresenter: PlaceTypesCellPresenterProtocol, PlaceTypesCellInteractorOutputProtocol {
    weak private var view: PlaceTypesCellViewProtocol?
    var interactor: PlaceTypesCellInteractorInputProtocol?
    private let router: PlaceTypesCellWireframeProtocol

    init(interface: PlaceTypesCellViewProtocol, interactor: PlaceTypesCellInteractorInputProtocol?, router: PlaceTypesCellWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func ready() {
    }

    func selected(type: LocationType) {
        router.selected(type: type)
    }
}
