//
//  PlaceTypesCellInteractor.swift
//  Places
//
//  Created Sebastian Cancinos on 22/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Toast_Swift

class PlaceTypesCellInteractor: PlaceTypesCellInteractorInputProtocol {
    weak var presenter: PlaceTypesCellInteractorOutputProtocol?
}
