//
//  PlaceTypesCellProtocols.swift
//  Places
//
//  Created Sebastian Cancinos on 22/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

// MARK: Wireframe -
protocol PlaceTypesCellWireframeProtocol: class {
    func selected(type: LocationType)
}
// MARK: Presenter -
protocol PlaceTypesCellPresenterProtocol: class {

    var interactor: PlaceTypesCellInteractorInputProtocol? { get set }
    func ready()
    func selected(type: LocationType)
}

// MARK: Interactor -
protocol PlaceTypesCellInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol PlaceTypesCellInteractorInputProtocol: class {

    var presenter: PlaceTypesCellInteractorOutputProtocol? { get set }

    /* Presenter -> Interactor */
}

// MARK: View -
protocol PlaceTypesCellViewProtocol: class {

    var presenter: PlaceTypesCellPresenterProtocol? { get set }

    /* Presenter -> ViewController */
}
