//
//  PlaceTypesCellViewController.swift
//  Places
//
//  Created Sebastian Cancinos on 22/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PlaceTypesCellView: UICollectionViewCell, PlaceTypesCellViewProtocol {

	var presenter: PlaceTypesCellPresenterProtocol?

    @IBOutlet weak var barButton: UIButton!
    @IBOutlet weak var restaurantButton: UIButton!
    @IBOutlet weak var cafeButton: UIButton!

    @IBAction func showBars() {
        presenter?.selected(type: .bar)
    }

    @IBAction func showRestaurant() {
        presenter?.selected(type: .restaurant)
    }

    @IBAction func showCafe() {
        presenter?.selected(type: .cafe)
    }
}
