//
//  PlaceTypesCellRouter.swift
//  Places
//
//  Created Sebastian Cancinos on 22/03/2020.
//  Copyright © 2020 sebacancinos. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PlaceTypesCellRouter: PlaceTypesCellWireframeProtocol {

    weak var view: UICollectionViewCell?
    weak var delegate: PlacesListDelegate?

    static func createModule(for view: PlaceTypesCellView) -> PlaceTypesCellRouter {
        // Change to get view from storyboard if not using progammatic UI
        let interactor = PlaceTypesCellInteractor()
        let router = PlaceTypesCellRouter()
        let presenter = PlaceTypesCellPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.view = view

        return router
    }

    func selected(type: LocationType) {
        delegate?.filter(by: type)
    }
}
